// ============================================================
// traits_congenital.js — Congenital/physical trait definitions, stat modifiers, and flavor text.
// ============================================================

const CONGENITAL_TRAITS = [
  {
    "id": "beauty_bad_1",
    "label": "Homely",
    "category": "congenital",
    "cost": -10,
    "group": "beauty_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_3","beauty_bad_2","beauty_good_2","beauty_good_1","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_bad_2",
    "label": "Ugly",
    "category": "congenital",
    "cost": -20,
    "group": "beauty_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_3","beauty_good_2","beauty_good_1","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_bad_3",
    "label": "Hideous",
    "category": "congenital",
    "cost": -30,
    "group": "beauty_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_2","beauty_good_2","beauty_good_1","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_good_1",
    "label": "Comely",
    "category": "congenital",
    "cost": 40,
    "group": "beauty_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_3","beauty_bad_2","beauty_good_2","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_good_2",
    "label": "Attractive",
    "category": "congenital",
    "cost": 80,
    "group": "beauty_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_3","beauty_bad_2","beauty_good_1","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_good_3",
    "label": "Stunning",
    "category": "congenital",
    "cost": 120,
    "group": "beauty_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_3","beauty_bad_2","beauty_good_2","beauty_good_1"],
    "compat": {}
  },
  {
    "id": "intellect_bad_1",
    "label": "Slow",
    "category": "congenital",
    "cost": -15,
    "group": "intellect_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_good_3","shrewd","intellect_bad_3","intellect_good_1","intellect_good_2","intellect_bad_2"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  {
    "id": "intellect_bad_2",
    "label": "Dim",
    "category": "congenital",
    "cost": -30,
    "group": "intellect_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_good_3","shrewd","intellect_bad_1","intellect_bad_3","intellect_good_1","intellect_good_2"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  {
    "id": "intellect_bad_3",
    "label": "Imbecile",
    "category": "congenital",
    "cost": -45,
    "group": "intellect_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_good_3","shrewd","intellect_bad_1","intellect_good_1","intellect_good_2","intellect_bad_2"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  {
    "id": "intellect_good_1",
    "label": "Sharp",
    "category": "congenital",
    "cost": 80,
    "group": "intellect_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_good_3","intellect_bad_1","intellect_bad_3","intellect_good_2","intellect_bad_2"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  {
    "id": "intellect_good_2",
    "label": "Quick",
    "category": "congenital",
    "cost": 160,
    "group": "intellect_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_good_3","intellect_bad_1","intellect_bad_3","intellect_good_1","intellect_bad_2"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  {
    "id": "intellect_good_3",
    "label": "Genius",
    "category": "congenital",
    "cost": 240,
    "group": "intellect_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_bad_1","intellect_bad_3","intellect_good_1","intellect_good_2","intellect_bad_2"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  {
    "id": "physique_bad_1",
    "label": "Weak Frame",
    "category": "congenital",
    "cost": -15,
    "group": "physique_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["physique_good_3","physique_bad_2","physique_bad_3","physique_good_2","physique_good_1","strong"],
    "compat": {}
  },
  {
    "id": "physique_bad_2",
    "label": "Feeble",
    "category": "congenital",
    "cost": -30,
    "group": "physique_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["physique_bad_1","physique_good_3","physique_bad_3","physique_good_2","physique_good_1","strong"],
    "compat": {}
  },
  {
    "id": "physique_bad_3",
    "label": "Frail",
    "category": "congenital",
    "cost": -45,
    "group": "physique_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["physique_bad_1","physique_good_3","physique_bad_2","physique_good_2","physique_good_1","strong"],
    "compat": {}
  },
  {
    "id": "physique_good_1",
    "label": "Able",
    "category": "congenital",
    "cost": 60,
    "group": "physique_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["physique_bad_1","physique_good_3","physique_bad_2","physique_bad_3","physique_good_2","spindly"],
    "compat": {}
  },
  {
    "id": "physique_good_2",
    "label": "Robust",
    "category": "congenital",
    "cost": 120,
    "group": "physique_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["physique_bad_1","physique_good_3","physique_bad_2","physique_bad_3","spindly","physique_good_1"],
    "compat": {}
  },
  {
    "id": "physique_good_3",
    "label": "Herculean",
    "category": "congenital",
    "cost": 180,
    "group": "physique_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["physique_bad_1","physique_bad_2","physique_bad_3","spindly","physique_good_2","physique_good_1"],
    "compat": {}
  },
  {
    "id": "pure_blooded",
    "label": "Pure Blooded",
    "category": "congenital",
    "cost": 50,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "fecund",
    "label": "Fecund",
    "category": "congenital",
    "cost": 50,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": ["infertile"],
    "compat": {}
  },
  {
    "id": "strong",
    "label": "Strong",
    "category": "congenital",
    "cost": 50,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": true,
    "opposites": ["physique_bad_1","physique_bad_2","physique_bad_3"],
    "compat": {}
  },
  {
    "id": "shrewd",
    "label": "Shrewd",
    "category": "congenital",
    "cost": 50,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": true,
    "opposites": ["intellect_bad_1","intellect_bad_3","intellect_bad_2"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  {
    "id": "clubfooted",
    "label": "Clubfooted",
    "category": "congenital",
    "cost": 0,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "hunchbacked",
    "label": "Hunchbacked",
    "category": "congenital",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "lisping",
    "label": "Lisping",
    "category": "congenital",
    "cost": -5,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "stuttering",
    "label": "Stuttering",
    "category": "congenital",
    "cost": -5,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "dwarf",
    "label": "Dwarf",
    "category": "congenital",
    "cost": 0,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": ["giant"],
    "compat": {}
  },
  {
    "id": "giant",
    "label": "Giant",
    "category": "congenital",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": ["dwarf"],
    "compat": {}
  },
  {
    "id": "inbred",
    "label": "Inbred",
    "category": "congenital",
    "cost": -30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "weak",
    "label": "Weak",
    "category": "congenital",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": true,
    "opposites": ["physique_good_2","physique_good_1","strong","physique_good_3"],
    "compat": {}
  },
  {
    "id": "dull",
    "label": "Dull",
    "category": "congenital",
    "cost": -20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": true,
    "opposites": ["intellect_good_1","shrewd","intellect_good_2","intellect_good_3"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  {
    "id": "spindly",
    "label": "Spindly",
    "category": "congenital",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": ["physique_good_2","physique_good_3","physique_good_1"],
    "compat": {}
  },
  {
    "id": "scaly",
    "label": "Scaly",
    "category": "congenital",
    "cost": 0,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "albino",
    "label": "Albino",
    "category": "congenital",
    "cost": 0,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "wheezing",
    "label": "Wheezing",
    "category": "congenital",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "bleeder",
    "label": "Bleeder",
    "category": "congenital",
    "cost": -20,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "infertile",
    "label": "Infertile",
    "category": "congenital",
    "cost": 0,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": true,
    "opposites": ["fecund"],
    "compat": {}
  },
  {
    "id": "magic_affinity",
    "label": "Magic Affinity",
    "category": "congenital",
    "cost": 125,
    "group": null,
    "level": null,
    "genetic": true,
    "physical": false,
    "opposites": [],
    "compat": {
        "shrewd": 10,
        "intellect_good_1": 5,
        "intellect_good_2": 10,
        "intellect_good_3": 15,
        "lifestyle_mystic": 15,
        "witch": 15,
        "scholar": 10,
        "talented_mage": 20
      }
  }
];

const CONGENITAL_STATS = {
  pure_blooded: { constitution: 1 },
  fecund: { constitution: 1 },
  wheezing: { constitution: -2, dexterity: -1, athletics: -2, survival: -1 },
  bleeder: { constitution: -1 },
  albino: { perception: 1 },
  beauty_bad_1: { diplomacy: -1, charisma: -1 },
  beauty_bad_2: { diplomacy: -2, charisma: -2 },
  beauty_bad_3: { diplomacy: -3, charisma: -3 },
  beauty_good_1: { diplomacy: 1, charisma: 1 },
  beauty_good_2: { diplomacy: 2, charisma: 2 },
  beauty_good_3: { diplomacy: 3, charisma: 3 },
  intellect_bad_1: { stewardship: -2, martial: -2, intrigue: -2, diplomacy: -2, learning: -2, intelligence: -2, wisdom: -1 },
  intellect_bad_2: { stewardship: -4, martial: -4, intrigue: -4, diplomacy: -4, learning: -4, intelligence: -4, wisdom: -2 },
  intellect_bad_3: { stewardship: -8, martial: -8, intrigue: -8, diplomacy: -8, learning: -8, intelligence: -6, wisdom: -3 },
  intellect_good_1: { stewardship: 1, martial: 1, intrigue: 1, diplomacy: 1, learning: 1, intelligence: 2, wisdom: 1 },
  intellect_good_2: { stewardship: 3, martial: 3, intrigue: 3, diplomacy: 3, learning: 3, intelligence: 4, wisdom: 2 },
  intellect_good_3: { stewardship: 5, martial: 5, intrigue: 5, diplomacy: 5, learning: 5, intelligence: 6, wisdom: 3 },
  physique_bad_1: { prowess: -2, strength: -1, dexterity: -1, constitution: -1, athletics: -1 },
  physique_bad_2: { prowess: -4, strength: -2, dexterity: -2, constitution: -2, athletics: -2 },
  physique_bad_3: { prowess: -6, strength: -3, dexterity: -3, constitution: -3, athletics: -3 },
  physique_good_1: { prowess: 2, strength: 1, dexterity: 1, constitution: 1, athletics: 1 },
  physique_good_2: { prowess: 4, strength: 2, dexterity: 2, constitution: 2, athletics: 2 },
  physique_good_3: { prowess: 8, strength: 4, dexterity: 3, constitution: 3, athletics: 4 },
  strong: { prowess: 4, strength: 3, athletics: 2, intimidation: 1 },
  shrewd: { stewardship: 2, martial: 2, intrigue: 2, diplomacy: 2, learning: 2, intelligence: 3, wisdom: 2, investigation: 2, insight: 2 },
  clubfooted: { prowess: -2, dexterity: -3, athletics: -2, acrobatics: -2, stealth: -2 },
  hunchbacked: { prowess: -2, dexterity: -1, athletics: -1, stealth: -1 },
  lisping: { diplomacy: -2, charisma: -1, performance: -1, persuasion: -1 },
  stuttering: { diplomacy: -2, charisma: -1, performance: -1 },
  dwarf: { prowess: -4, strength: -1, dexterity: -1, constitution: 1, stealth: 1 },
  giant: { prowess: 6, strength: 3, dexterity: -1, athletics: 2, intimidation: 2 },
  inbred: { stewardship: -5, martial: -5, intrigue: -5, diplomacy: -5, learning: -5, prowess: -2, intelligence: -2, wisdom: -2, constitution: -1 },
  weak: { prowess: -2, strength: -2, constitution: -1, athletics: -1 },
  dull: { stewardship: -2, martial: -2, intrigue: -2, diplomacy: -2, learning: -2, intelligence: -2 },
  spindly: { prowess: -1, strength: -1, dexterity: 1, constitution: -1 },
  magic_affinity: { learning: 2, arcana: 3, intelligence: 1, wisdom: 1 }
};

const CONGENITAL_FLAVOR = {
  beauty_bad_1: '{name} is plain in appearance — which means people often underestimate them. That can be its own advantage.',
  beauty_bad_2: '{name}\'s looks draw attention for the wrong reasons. They have learned to lead with everything else.',
  beauty_bad_3: '{name} bears a difficult countenance. The world is not always kind about it.',
  beauty_good_1: '{name} is easy on the eyes — a fact that opens certain doors.',
  beauty_good_2: '{name} turns heads. Beauty like theirs is hard to ignore, which can be a blessing and a burden.',
  beauty_good_3: '{name} is striking. The kind of face that gets written about in letters.',
  intellect_bad_1: '{name}\'s thoughts come slowly. They are not fast, but sometimes thoroughness wins the day.',
  intellect_bad_2: '{name} struggles to grasp what others find obvious. Life requires more patience — both from and with them.',
  intellect_bad_3: '{name} has significant intellectual limitations. Others have been known to take advantage of that.',
  intellect_good_1: '{name} catches on quickly. They are sharper than they usually let on.',
  intellect_good_2: '{name} is clearly gifted. Their mind moves with unusual efficiency.',
  intellect_good_3: '{name} has an extraordinary mind. Those around them know it; some find it unnerving.',
  physique_bad_1: '{name} is not built for hardship. They find physical demands taxing in ways others do not.',
  physique_bad_2: '{name}\'s body is fragile in notable ways. They manage, but not without effort.',
  physique_bad_3: '{name} is physically weak. They compensate with everything else they have.',
  physique_good_1: '{name} is above average in strength and health. Their body serves them well.',
  physique_good_2: '{name} is notably strong — the kind of strong you notice when they work or fight.',
  physique_good_3: '{name} has been blessed with an exceptional physique. Built for whatever the world demands.',
  pure_blooded: '{name} comes from a line that has been carefully maintained. Their heritage runs clear.',
  fecund: '{name} is remarkably fertile — a fact that has shaped many plans around them, with or without their consent.',
  strong: '{name} possesses uncommon physical strength. It is not something they are shy about putting to use.',
  shrewd: '{name} has a mind for angles. They read situations and people with uncanny accuracy.',
  clubfooted: '{name} carries the mark of clubfoot. It has slowed their body, but rarely their resolve.',
  hunchbacked: '{name} bears a hunch that the world has tried to define them by. They have other ideas.',
  lisping: '{name} speaks with a lisp — a quirk that some find charming, others condescending about. They have learned to navigate.',
  stuttering: '{name}\'s words sometimes catch in the throat. It has never stopped them from speaking their mind.',
  dwarf: '{name} is a dwarf among others — different by measure, not by worth.',
  giant: '{name} stands above the crowd in literal terms. It is hard to be overlooked when you tower over the room.',
  inbred: 'The bloodline that produced {name} was perhaps kept too close. There are... complications.',
  weak: '{name} lacks physical robustness. They are not built for the fight, but that is not the only kind of strength.',
  dull: '{name}\'s mind works against them at times. Life requires more patience — both from and with them.',
  spindly: '{name} is slight in form, almost fragile-looking. Do not let it fool you.',
  scaly: '{name} bears skin with an unusual texture — something between ordinary and uncanny.',
  albino: '{name} lacks pigment — pale as milk, white-haired, a subject of whispers in certain circles.',
  wheezing: '{name}\'s lungs have never been their strongest feature. Every season is a negotiation.',
  bleeder: '{name}\'s blood does not clot as it should. Minor wounds become greater concerns.',
  infertile: '{name} cannot bear children. Whether they grieve this, accept it, or see it as freedom is their story to tell.',
  magic_affinity: '{name} carries something not everyone is born with — an innate attunement to the forces beneath the surface of the world. Magic does not feel foreign to them. It feels like speaking a language they already knew.'
};
