// ============================================================
// traits_congenital.js — Congenital/physical trait definitions, stat modifiers, and flavor text.
// ============================================================

const CONGENITAL_TRAITS = [
  // ── Beauty Bad ────────────────────────────────────────────
  {
    "id": "beauty_bad_1",
    "label": "Homely",
    "category": "congenital",
    "cost": -10,
    "group": "beauty_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_2","beauty_bad_3","beauty_good_1","beauty_good_2","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_bad_2",
    "label": "Ugly",
    "category": "congenital",
    "cost": -20,
    "group": "beauty_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_3","beauty_good_1","beauty_good_2","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_bad_3",
    "label": "Hideous",
    "category": "congenital",
    "cost": -30,
    "group": "beauty_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_2","beauty_good_1","beauty_good_2","beauty_good_3"],
    "compat": {}
  },
  // ── Beauty Good ───────────────────────────────────────────
  {
    "id": "beauty_good_1",
    "label": "Comely",
    "category": "congenital",
    "cost": 40,
    "group": "beauty_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_2","beauty_bad_3","beauty_good_2","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_good_2",
    "label": "Attractive",
    "category": "congenital",
    "cost": 80,
    "group": "beauty_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_2","beauty_bad_3","beauty_good_1","beauty_good_3"],
    "compat": {}
  },
  {
    "id": "beauty_good_3",
    "label": "Stunning",
    "category": "congenital",
    "cost": 120,
    "group": "beauty_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["beauty_bad_1","beauty_bad_2","beauty_bad_3","beauty_good_1","beauty_good_2"],
    "compat": {}
  },
  // ── Intellect Bad ─────────────────────────────────────────
  // Level 1–4: Slow → Dull → Dim → Imbecile
  {
    "id": "intellect_bad_1",
    "label": "Slow",
    "category": "congenital",
    "cost": -15,
    "group": "intellect_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["dull","intellect_bad_2","intellect_bad_3","shrewd","intellect_good_1","intellect_good_2","intellect_good_3"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  {
    "id": "dull",
    "label": "Dull",
    "category": "congenital",
    "cost": -20,
    "group": "intellect_bad",
    "level": 2,
    "genetic": false,
    "physical": true,
    "opposites": ["intellect_bad_1","intellect_bad_2","intellect_bad_3","shrewd","intellect_good_1","intellect_good_2","intellect_good_3"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  {
    "id": "intellect_bad_2",
    "label": "Dim",
    "category": "congenital",
    "cost": -30,
    "group": "intellect_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_bad_1","dull","intellect_bad_3","shrewd","intellect_good_1","intellect_good_2","intellect_good_3"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  {
    "id": "intellect_bad_3",
    "label": "Imbecile",
    "category": "congenital",
    "cost": -45,
    "group": "intellect_bad",
    "level": 4,
    "genetic": true,
    "physical": true,
    "opposites": ["intellect_bad_1","dull","intellect_bad_2","shrewd","intellect_good_1","intellect_good_2","intellect_good_3"],
    "compat": {
        "intellect_bad_1": 15,
        "intellect_bad_2": 15,
        "intellect_bad_3": 15,
        "dull": 15,
        "intellect_good_1": -15,
        "intellect_good_2": -15,
        "intellect_good_3": -15,
        "shrewd": -15
      }
  },
  // ── Intellect Good ────────────────────────────────────────
  // Level 1–4: Shrewd → Sharp → Quick → Genius
  {
    "id": "shrewd",
    "label": "Shrewd",
    "category": "congenital",
    "cost": 50,
    "group": "intellect_good",
    "level": 1,
    "genetic": false,
    "physical": true,
    "opposites": ["intellect_good_1","intellect_good_2","intellect_good_3","dull","intellect_bad_1","intellect_bad_2","intellect_bad_3"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  {
    "id": "intellect_good_1",
    "label": "Sharp",
    "category": "congenital",
    "cost": 80,
    "group": "intellect_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["shrewd","intellect_good_2","intellect_good_3","dull","intellect_bad_1","intellect_bad_2","intellect_bad_3"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  {
    "id": "intellect_good_2",
    "label": "Quick",
    "category": "congenital",
    "cost": 160,
    "group": "intellect_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["shrewd","intellect_good_1","intellect_good_3","dull","intellect_bad_1","intellect_bad_2","intellect_bad_3"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  {
    "id": "intellect_good_3",
    "label": "Genius",
    "category": "congenital",
    "cost": 240,
    "group": "intellect_good",
    "level": 4,
    "genetic": true,
    "physical": true,
    "opposites": ["shrewd","intellect_good_1","intellect_good_2","dull","intellect_bad_1","intellect_bad_2","intellect_bad_3"],
    "compat": {
        "intellect_good_1": 15,
        "intellect_good_2": 15,
        "intellect_good_3": 15,
        "shrewd": 15,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "dull": -15
      }
  },
  // ── Physique Bad ──────────────────────────────────────────
  // Level 1–4: Weak → Weak Frame → Feeble → Frail
  {
    "id": "weak",
    "label": "Weak",
    "category": "congenital",
    "cost": -10,
    "group": "physique_bad",
    "level": 1,
    "genetic": false,
    "physical": true,
    "opposites": ["physique_bad_1","physique_bad_2","physique_bad_3","strong","physique_good_1","physique_good_2","physique_good_3"],
    "compat": {}
  },
  {
    "id": "physique_bad_1",
    "label": "Weak Frame",
    "category": "congenital",
    "cost": -15,
    "group": "physique_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["weak","physique_bad_2","physique_bad_3","strong","physique_good_1","physique_good_2","physique_good_3"],
    "compat": {}
  },
  {
    "id": "physique_bad_2",
    "label": "Feeble",
    "category": "congenital",
    "cost": -30,
    "group": "physique_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["weak","physique_bad_1","physique_bad_3","strong","physique_good_1","physique_good_2","physique_good_3"],
    "compat": {}
  },
  {
    "id": "physique_bad_3",
    "label": "Frail",
    "category": "congenital",
    "cost": -45,
    "group": "physique_bad",
    "level": 4,
    "genetic": true,
    "physical": true,
    "opposites": ["weak","physique_bad_1","physique_bad_2","strong","physique_good_1","physique_good_2","physique_good_3"],
    "compat": {}
  },
  // ── Physique Good ─────────────────────────────────────────
  // Level 1–4: Strong → Able → Robust → Herculean
  {
    "id": "strong",
    "label": "Strong",
    "category": "congenital",
    "cost": 50,
    "group": "physique_good",
    "level": 1,
    "genetic": false,
    "physical": true,
    "opposites": ["physique_good_1","physique_good_2","physique_good_3","weak","physique_bad_1","physique_bad_2","physique_bad_3"],
    "compat": {}
  },
  {
    "id": "physique_good_1",
    "label": "Able",
    "category": "congenital",
    "cost": 60,
    "group": "physique_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["strong","physique_good_2","physique_good_3","weak","physique_bad_1","physique_bad_2","physique_bad_3","spindly"],
    "compat": {}
  },
  {
    "id": "physique_good_2",
    "label": "Robust",
    "category": "congenital",
    "cost": 120,
    "group": "physique_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["strong","physique_good_1","physique_good_3","weak","physique_bad_1","physique_bad_2","physique_bad_3","spindly"],
    "compat": {}
  },
  {
    "id": "physique_good_3",
    "label": "Herculean",
    "category": "congenital",
    "cost": 180,
    "group": "physique_good",
    "level": 4,
    "genetic": true,
    "physical": true,
    "opposites": ["strong","physique_good_1","physique_good_2","weak","physique_bad_1","physique_bad_2","physique_bad_3","spindly"],
    "compat": {}
  },
  // ── Speech Bad ────────────────────────────────────────────
  {
    "id": "lisping",
    "label": "Lisping",
    "category": "congenital",
    "cost": -5,
    "group": "speech_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["stuttering","speech_good_1","speech_good_2"],
    "compat": {}
  },
  {
    "id": "stuttering",
    "label": "Stuttering",
    "category": "congenital",
    "cost": -5,
    "group": "speech_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["lisping","speech_good_1","speech_good_2"],
    "compat": {}
  },
  // ── Speech Good ───────────────────────────────────────────
  {
    "id": "speech_good_1",
    "label": "Articulate",
    "category": "congenital",
    "cost": 30,
    "group": "speech_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["speech_good_2","lisping","stuttering"],
    "compat": {}
  },
  {
    "id": "speech_good_2",
    "label": "Well-Spoken",
    "category": "congenital",
    "cost": 60,
    "group": "speech_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["speech_good_1","lisping","stuttering"],
    "compat": {}
  },
  // ── Health Bad ────────────────────────────────────────────
  {
    "id": "bleeder",
    "label": "Bleeder",
    "category": "congenital",
    "cost": -20,
    "group": "health_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["chronic_ailment","diseased","hardy","resilient","iron_constitution"],
    "compat": {}
  },
  {
    "id": "chronic_ailment",
    "label": "Chronic Ailment",
    "category": "congenital",
    "cost": -30,
    "group": "health_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["bleeder","diseased","hardy","resilient","iron_constitution"],
    "compat": {}
  },
  {
    "id": "diseased",
    "label": "Diseased",
    "category": "congenital",
    "cost": -45,
    "group": "health_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["bleeder","chronic_ailment","hardy","resilient","iron_constitution"],
    "compat": {}
  },
  // ── Health Good ───────────────────────────────────────────
  {
    "id": "hardy",
    "label": "Hardy",
    "category": "congenital",
    "cost": 30,
    "group": "health_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["resilient","iron_constitution","bleeder","chronic_ailment","diseased"],
    "compat": {}
  },
  {
    "id": "resilient",
    "label": "Resilient",
    "category": "congenital",
    "cost": 60,
    "group": "health_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["hardy","iron_constitution","bleeder","chronic_ailment","diseased"],
    "compat": {}
  },
  {
    "id": "iron_constitution",
    "label": "Iron Constitution",
    "category": "congenital",
    "cost": 90,
    "group": "health_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["hardy","resilient","bleeder","chronic_ailment","diseased"],
    "compat": {}
  },
  // ── Fertility Bad ─────────────────────────────────────────
  {
    "id": "infertile",
    "label": "Infertile",
    "category": "congenital",
    "cost": 0,
    "group": "fertility_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["fecund","virile"],
    "compat": {}
  },
  // ── Fertility Good ────────────────────────────────────────
  {
    "id": "fecund",
    "label": "Fecund",
    "category": "congenital",
    "cost": 50,
    "group": "fertility_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["virile","infertile"],
    "compat": {}
  },
  {
    "id": "virile",
    "label": "Virile",
    "category": "congenital",
    "cost": 70,
    "group": "fertility_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["fecund","infertile"],
    "compat": {}
  },
  // ── Bloodline Bad ─────────────────────────────────────────
  {
    "id": "inbred",
    "label": "Inbred",
    "category": "congenital",
    "cost": -30,
    "group": "bloodline_bad",
    "level": 1,
    "genetic": false,
    "physical": true,
    "opposites": ["pure_blooded"],
    "compat": {}
  },
  // ── Bloodline Good ────────────────────────────────────────
  {
    "id": "pure_blooded",
    "label": "Pure Blooded",
    "category": "congenital",
    "cost": 50,
    "group": "bloodline_good",
    "level": 1,
    "genetic": false,
    "physical": true,
    "opposites": ["inbred"],
    "compat": {}
  },
  // ── Mobility Bad ──────────────────────────────────────────
  {
    "id": "clubfooted",
    "label": "Clubfooted",
    "category": "congenital",
    "cost": 0,
    "group": "mobility_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["spindly","light_footed","graceful"],
    "compat": {}
  },
  {
    "id": "spindly",
    "label": "Spindly",
    "category": "congenital",
    "cost": -10,
    "group": "mobility_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["clubfooted","light_footed","graceful","strong","physique_good_1","physique_good_2","physique_good_3"],
    "compat": {}
  },
  // ── Mobility Good ─────────────────────────────────────────
  {
    "id": "light_footed",
    "label": "Light-Footed",
    "category": "congenital",
    "cost": 25,
    "group": "mobility_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["graceful","clubfooted","spindly"],
    "compat": {}
  },
  {
    "id": "graceful",
    "label": "Graceful",
    "category": "congenital",
    "cost": 50,
    "group": "mobility_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["light_footed","clubfooted","spindly"],
    "compat": {}
  },
  // ── Respiration Bad ───────────────────────────────────────
  {
    "id": "wheezing",
    "label": "Wheezing",
    "category": "congenital",
    "cost": -10,
    "group": "respiration_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["breathless","strong_lungs","iron_lungs"],
    "compat": {}
  },
  {
    "id": "breathless",
    "label": "Breathless",
    "category": "congenital",
    "cost": -25,
    "group": "respiration_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["wheezing","strong_lungs","iron_lungs"],
    "compat": {}
  },
  // ── Respiration Good ──────────────────────────────────────
  {
    "id": "strong_lungs",
    "label": "Strong Lungs",
    "category": "congenital",
    "cost": 25,
    "group": "respiration_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["iron_lungs","wheezing","breathless"],
    "compat": {}
  },
  {
    "id": "iron_lungs",
    "label": "Iron Lungs",
    "category": "congenital",
    "cost": 50,
    "group": "respiration_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["strong_lungs","wheezing","breathless"],
    "compat": {}
  },
  // ── Form Bad ──────────────────────────────────────────────
  {
    "id": "scaly",
    "label": "Scaly",
    "category": "congenital",
    "cost": 0,
    "group": "form_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["albino","glowing_skin","radiant"],
    "compat": {}
  },
  {
    "id": "albino",
    "label": "Albino",
    "category": "congenital",
    "cost": 0,
    "group": "form_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["scaly","glowing_skin","radiant"],
    "compat": {}
  },
  {
    "id": "dwarf",
    "label": "Dwarf",
    "category": "congenital",
    "cost": 0,
    "group": "form_bad",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["giant"],
    "compat": {}
  },
  // ── Form Good ─────────────────────────────────────────────
  {
    "id": "glowing_skin",
    "label": "Glowing Skin",
    "category": "congenital",
    "cost": 20,
    "group": "form_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["radiant","scaly","albino"],
    "compat": {}
  },
  {
    "id": "radiant",
    "label": "Radiant",
    "category": "congenital",
    "cost": 40,
    "group": "form_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["glowing_skin","scaly","albino"],
    "compat": {}
  },
  {
    "id": "giant",
    "label": "Giant",
    "category": "congenital",
    "cost": 20,
    "group": "form_good",
    "level": 3,
    "genetic": true,
    "physical": true,
    "opposites": ["dwarf"],
    "compat": {}
  },
  // ── Posture Bad ───────────────────────────────────────────
  {
    "id": "slouching",
    "label": "Slouching",
    "category": "congenital",
    "cost": -5,
    "group": "posture_bad",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["hunchbacked","upright","regal_bearing"],
    "compat": {}
  },
  {
    "id": "hunchbacked",
    "label": "Hunchbacked",
    "category": "congenital",
    "cost": -10,
    "group": "posture_bad",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["slouching","upright","regal_bearing"],
    "compat": {}
  },
  // ── Posture Good ──────────────────────────────────────────
  {
    "id": "upright",
    "label": "Upright",
    "category": "congenital",
    "cost": 15,
    "group": "posture_good",
    "level": 1,
    "genetic": true,
    "physical": true,
    "opposites": ["regal_bearing","slouching","hunchbacked"],
    "compat": {}
  },
  {
    "id": "regal_bearing",
    "label": "Regal Bearing",
    "category": "congenital",
    "cost": 25,
    "group": "posture_good",
    "level": 2,
    "genetic": true,
    "physical": true,
    "opposites": ["upright","slouching","hunchbacked"],
    "compat": {}
  }
];

const CONGENITAL_STATS = {
  beauty_bad_1: { diplomacy: -1, charisma: -1 },
  beauty_bad_2: { diplomacy: -2, charisma: -2 },
  beauty_bad_3: { diplomacy: -3, charisma: -3 },
  beauty_good_1: { diplomacy: 1, charisma: 1 },
  beauty_good_2: { diplomacy: 2, charisma: 2 },
  beauty_good_3: { diplomacy: 3, charisma: 3 },
  intellect_bad_1: { stewardship: -2, martial: -2, intrigue: -2, diplomacy: -2, learning: -2, intelligence: -2, wisdom: -1 },
  dull:            { stewardship: -2, martial: -2, intrigue: -2, diplomacy: -2, learning: -2, intelligence: -2 },
  intellect_bad_2: { stewardship: -4, martial: -4, intrigue: -4, diplomacy: -4, learning: -4, intelligence: -4, wisdom: -2 },
  intellect_bad_3: { stewardship: -8, martial: -8, intrigue: -8, diplomacy: -8, learning: -8, intelligence: -6, wisdom: -3 },
  shrewd:           { stewardship: 2, martial: 2, intrigue: 2, diplomacy: 2, learning: 2, intelligence: 3, wisdom: 2, investigation: 2, insight: 2 },
  intellect_good_1: { stewardship: 1, martial: 1, intrigue: 1, diplomacy: 1, learning: 1, intelligence: 2, wisdom: 1 },
  intellect_good_2: { stewardship: 3, martial: 3, intrigue: 3, diplomacy: 3, learning: 3, intelligence: 4, wisdom: 2 },
  intellect_good_3: { stewardship: 5, martial: 5, intrigue: 5, diplomacy: 5, learning: 5, intelligence: 6, wisdom: 3 },
  weak:         { prowess: -2, strength: -2, constitution: -1, athletics: -1 },
  physique_bad_1: { prowess: -2, strength: -1, dexterity: -1, constitution: -1, athletics: -1 },
  physique_bad_2: { prowess: -4, strength: -2, dexterity: -2, constitution: -2, athletics: -2 },
  physique_bad_3: { prowess: -6, strength: -3, dexterity: -3, constitution: -3, athletics: -3 },
  strong:         { prowess: 4, strength: 3, athletics: 2, intimidation: 1 },
  physique_good_1: { prowess: 2, strength: 1, dexterity: 1, constitution: 1, athletics: 1 },
  physique_good_2: { prowess: 4, strength: 2, dexterity: 2, constitution: 2, athletics: 2 },
  physique_good_3: { prowess: 8, strength: 4, dexterity: 3, constitution: 3, athletics: 4 },
  speech_good_1: { diplomacy: 1, charisma: 1, persuasion: 1, performance: 1 },
  speech_good_2: { diplomacy: 2, charisma: 2, persuasion: 2, performance: 2 },
  lisping:   { diplomacy: -2, charisma: -1, performance: -1, persuasion: -1 },
  stuttering: { diplomacy: -2, charisma: -1, performance: -1 },
  bleeder:         { constitution: -1 },
  chronic_ailment: { constitution: -2, athletics: -1, survival: -1 },
  diseased:        { constitution: -3, strength: -1, dexterity: -1, athletics: -2 },
  hardy:           { constitution: 2, athletics: 1, survival: 1 },
  resilient:       { constitution: 3, athletics: 2, survival: 2 },
  iron_constitution: { constitution: 4, athletics: 3, survival: 3, strength: 1 },
  infertile: {},
  fecund:  { constitution: 1 },
  virile:  { constitution: 2 },
  inbred:       { stewardship: -5, martial: -5, intrigue: -5, diplomacy: -5, learning: -5, prowess: -2, intelligence: -2, wisdom: -2, constitution: -1 },
  pure_blooded: { constitution: 1 },
  clubfooted: { prowess: -2, dexterity: -3, athletics: -2, acrobatics: -2, stealth: -2 },
  spindly:    { prowess: -1, strength: -1, dexterity: 1, constitution: -1 },
  light_footed: { dexterity: 2, acrobatics: 2, stealth: 1 },
  graceful:     { dexterity: 3, acrobatics: 3, stealth: 2, performance: 1 },
  wheezing:   { constitution: -2, dexterity: -1, athletics: -2, survival: -1 },
  breathless: { constitution: -3, athletics: -3, survival: -2, dexterity: -1 },
  strong_lungs: { constitution: 2, athletics: 2, survival: 1 },
  iron_lungs:   { constitution: 3, athletics: 3, survival: 2 },
  dwarf: { prowess: -4, strength: -1, dexterity: -1, constitution: 1, stealth: 1 },
  giant: { prowess: 6, strength: 3, dexterity: -1, athletics: 2, intimidation: 2 },
  scaly:  {},
  albino: { perception: 1 },
  glowing_skin: { charisma: 1, diplomacy: 1 },
  radiant:      { charisma: 2, diplomacy: 2, intimidation: 1 },
  slouching:    { charisma: -1, diplomacy: -1 },
  hunchbacked:  { prowess: -2, dexterity: -1, athletics: -1, stealth: -1 },
  upright:      { charisma: 1, diplomacy: 1 },
  regal_bearing: { charisma: 2, diplomacy: 1, intimidation: 1 }
};

const CONGENITAL_FLAVOR = {
  beauty_bad_1: '{name} is plain in appearance — which means people often underestimate them. That can be its own advantage.',
  beauty_bad_2: '{name}\'s looks draw attention for the wrong reasons. They have learned to lead with everything else.',
  beauty_bad_3: '{name} bears a difficult countenance. The world is not always kind about it.',
  beauty_good_1: '{name} is easy on the eyes — a fact that opens certain doors.',
  beauty_good_2: '{name} turns heads. Beauty like theirs is hard to ignore, which can be a blessing and a burden.',
  beauty_good_3: '{name} is striking. The kind of face that gets written about in letters.',
  intellect_bad_1: '{name}\'s thoughts come slowly. They are not fast, but sometimes thoroughness wins the day.',
  dull: '{name}\'s practical wits work against them at times. They miss things others notice without trying.',
  intellect_bad_2: '{name} struggles to grasp what others find obvious. Life requires more patience — both from and with them.',
  intellect_bad_3: '{name} has significant intellectual limitations. Others have been known to take advantage of that.',
  shrewd: '{name} has a mind for angles. They read situations and people with uncanny accuracy.',
  intellect_good_1: '{name} catches on quickly. They are sharper than they usually let on.',
  intellect_good_2: '{name} is clearly gifted. Their mind moves with unusual efficiency.',
  intellect_good_3: '{name} has an extraordinary mind. Those around them know it; some find it unnerving.',
  weak: '{name} lacks physical strength. They are not built for the fight, but that is not the only kind of power.',
  physique_bad_1: '{name} is not built for hardship. They find physical demands taxing in ways others do not.',
  physique_bad_2: '{name}\'s body is fragile in notable ways. They manage, but not without effort.',
  physique_bad_3: '{name} is physically weak. They compensate with everything else they have.',
  strong: '{name} possesses uncommon physical strength. It is not something they are shy about putting to use.',
  physique_good_1: '{name} is above average in body and frame. Their constitution serves them well.',
  physique_good_2: '{name} is notably fit — the kind of physical presence you notice when they work or fight.',
  physique_good_3: '{name} has been blessed with an exceptional physique. Built for whatever the world demands.',
  lisping: '{name} speaks with a lisp — a quirk that some find charming, others condescending about. They have learned to navigate.',
  stuttering: '{name}\'s words sometimes catch in the throat. It has never stopped them from speaking their mind.',
  speech_good_1: '{name} speaks with clarity and purpose. Words come naturally to them, and people tend to listen.',
  speech_good_2: '{name} has a gift for language. Every word lands where intended — a skill that turns conversations into outcomes.',
  bleeder: '{name}\'s blood does not clot as it should. Minor wounds become greater concerns.',
  chronic_ailment: '{name} has never been fully well. A persistent ailment colors their days — managed, rarely absent, never forgotten.',
  diseased: '{name} carries a lasting illness that shapes how they move through the world. Some seasons are better than others. Most are not.',
  hardy: '{name} is built to endure. Minor ailments pass quickly. They bounce back from what would sideline others.',
  resilient: '{name} has a body that fights back. They recover well and resist illness with unusual stubbornness.',
  iron_constitution: '{name}\'s constitution is exceptional — almost defiant. Illness takes note and moves on.',
  infertile: '{name} cannot bear children. Whether they grieve this, accept it, or see it as freedom is their story to tell.',
  fecund: '{name} is remarkably fertile — a fact that has shaped many plans around them, with or without their consent.',
  virile: '{name} is exceptionally fertile, a trait that carries weight in bloodlines and inheritance alike.',
  inbred: 'The bloodline that produced {name} was perhaps kept too close. There are... complications.',
  pure_blooded: '{name} comes from a line that has been carefully maintained. Their heritage runs clear.',
  clubfooted: '{name} carries the mark of clubfoot. It has slowed their body, but rarely their resolve.',
  spindly: '{name} is slight in form, almost fragile-looking. Do not let it fool you.',
  light_footed: '{name} moves with quiet ease. Light on their feet in ways that suggest either training or something else entirely.',
  graceful: '{name}\'s movements have a quality that goes beyond coordination. They occupy space with unusual precision.',
  wheezing: '{name}\'s lungs have never been their strongest feature. Every season is a negotiation.',
  breathless: '{name} runs out of air with alarming ease. Sustained exertion is not something their lungs accommodate gracefully.',
  strong_lungs: '{name} breathes deep and easy. Where others falter, they keep pace.',
  iron_lungs: '{name} has remarkable endurance when it comes to exertion. Where others wheeze and falter, they keep pace without commentary.',
  dwarf: '{name} is a dwarf among others — different by measure, not by worth.',
  giant: '{name} stands above the crowd in literal terms. It is hard to be overlooked when you tower over the room.',
  scaly: '{name} bears skin with an unusual texture — something between ordinary and uncanny.',
  albino: '{name} lacks pigment — pale as milk, white-haired, a subject of whispers in certain circles.',
  glowing_skin: '{name}\'s complexion has an unusual luminescence — a quality that draws a second glance and rarely a simple explanation.',
  radiant: '{name} radiates something beyond ordinary beauty. There is a quality to their presence that people struggle to name.',
  slouching: '{name} carries themselves with a certain disregard for posture. First impressions have occasionally suffered for it.',
  hunchbacked: '{name} bears a hunch that the world has tried to define them by. They have other ideas.',
  upright: '{name} stands straight and carries themselves with quiet self-assurance. It is noticed before they even speak.',
  regal_bearing: '{name} carries themselves with a natural authority. Posture that says nothing — and somehow everything.'
};
