// ============================================================
// traits_education.js — Education trait definitions, stat modifiers, and flavor text.
// ============================================================

const EDUCATION_TRAITS = [
  {
    "id": "education_intrigue_1",
    "label": "Intrigue: Trained",
    "category": "education",
    "cost": 0,
    "group": "education_intrigue",
    "level": 1,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_intrigue_2",
    "label": "Intrigue: Competent",
    "category": "education",
    "cost": 20,
    "group": "education_intrigue",
    "level": 2,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_intrigue_3",
    "label": "Intrigue: Expert",
    "category": "education",
    "cost": 40,
    "group": "education_intrigue",
    "level": 3,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_intrigue_4",
    "label": "Intrigue: Master",
    "category": "education",
    "cost": 80,
    "group": "education_intrigue",
    "level": 4,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_intrigue_5",
    "label": "Intrigue: Legend",
    "category": "education",
    "cost": 150,
    "group": "education_intrigue",
    "level": 5,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_diplomacy_1",
    "label": "Diplomacy: Trained",
    "category": "education",
    "cost": 0,
    "group": "education_diplomacy",
    "level": 1,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_diplomacy_2",
    "label": "Diplomacy: Competent",
    "category": "education",
    "cost": 20,
    "group": "education_diplomacy",
    "level": 2,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_diplomacy_3",
    "label": "Diplomacy: Expert",
    "category": "education",
    "cost": 40,
    "group": "education_diplomacy",
    "level": 3,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_diplomacy_4",
    "label": "Diplomacy: Master",
    "category": "education",
    "cost": 80,
    "group": "education_diplomacy",
    "level": 4,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_diplomacy_5",
    "label": "Diplomacy: Legend",
    "category": "education",
    "cost": 150,
    "group": "education_diplomacy",
    "level": 5,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_stewardship_1",
    "label": "Stewardship: Trained",
    "category": "education",
    "cost": 0,
    "group": "education_stewardship",
    "level": 1,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_stewardship_2",
    "label": "Stewardship: Competent",
    "category": "education",
    "cost": 20,
    "group": "education_stewardship",
    "level": 2,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_stewardship_3",
    "label": "Stewardship: Expert",
    "category": "education",
    "cost": 40,
    "group": "education_stewardship",
    "level": 3,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_stewardship_4",
    "label": "Stewardship: Master",
    "category": "education",
    "cost": 80,
    "group": "education_stewardship",
    "level": 4,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_stewardship_5",
    "label": "Stewardship: Legend",
    "category": "education",
    "cost": 150,
    "group": "education_stewardship",
    "level": 5,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_martial_1",
    "label": "Martial: Trained",
    "category": "education",
    "cost": 0,
    "group": "education_martial",
    "level": 1,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_martial_2",
    "label": "Martial: Competent",
    "category": "education",
    "cost": 20,
    "group": "education_martial",
    "level": 2,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_martial_3",
    "label": "Martial: Expert",
    "category": "education",
    "cost": 40,
    "group": "education_martial",
    "level": 3,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_martial_4",
    "label": "Martial: Master",
    "category": "education",
    "cost": 80,
    "group": "education_martial",
    "level": 4,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_martial_5",
    "label": "Martial: Legend",
    "category": "education",
    "cost": 150,
    "group": "education_martial",
    "level": 5,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_learning_1",
    "label": "Learning: Trained",
    "category": "education",
    "cost": 0,
    "group": "education_learning",
    "level": 1,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_learning_2",
    "label": "Learning: Competent",
    "category": "education",
    "cost": 20,
    "group": "education_learning",
    "level": 2,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_learning_3",
    "label": "Learning: Expert",
    "category": "education",
    "cost": 40,
    "group": "education_learning",
    "level": 3,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_learning_4",
    "label": "Learning: Master",
    "category": "education",
    "cost": 80,
    "group": "education_learning",
    "level": 4,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "education_learning_5",
    "label": "Learning: Legend",
    "category": "education",
    "cost": 150,
    "group": "education_learning",
    "level": 5,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  }
];

const EDUCATION_STATS = {
  education_intrigue_1: { intrigue: 2 },
  education_intrigue_2: { intrigue: 4 },
  education_intrigue_3: { intrigue: 6 },
  education_intrigue_4: { intrigue: 8 },
  education_intrigue_5: { intrigue: 10, diplomacy: 3 },
  education_diplomacy_1: { diplomacy: 2 },
  education_diplomacy_2: { diplomacy: 4 },
  education_diplomacy_3: { diplomacy: 6 },
  education_diplomacy_4: { diplomacy: 8 },
  education_diplomacy_5: { martial: 3, diplomacy: 10 },
  education_stewardship_1: { stewardship: 2 },
  education_stewardship_2: { stewardship: 4 },
  education_stewardship_3: { stewardship: 6 },
  education_stewardship_4: { stewardship: 8 },
  education_stewardship_5: { stewardship: 10, learning: 3 },
  education_martial_1: { martial: 2 },
  education_martial_2: { martial: 4 },
  education_martial_3: { martial: 6 },
  education_martial_4: { martial: 8 },
  education_martial_5: { stewardship: 3, martial: 10 },
  education_learning_1: { learning: 2 },
  education_learning_2: { learning: 4 },
  education_learning_3: { learning: 6 },
  education_learning_4: { learning: 8 },
  education_learning_5: { intrigue: 3, learning: 10 }
};

const EDUCATION_FLAVOR = {
  education_intrigue_1: '{name} has learned the basics of reading rooms and keeping secrets. A foothold in the shadowy arts.',
  education_intrigue_2: '{name} is no novice in the art of subterfuge. They can read between lines and leave none of their own.',
  education_intrigue_3: '{name} has honed intrigue into a skill few can match. They know who is watching, and who is lying.',
  education_intrigue_4: '{name} commands the shadows with ease. Few schemes unfold without their awareness, or participation.',
  education_intrigue_5: '{name} is a legend in the game of whispers and knives. They did not just learn intrigue — they became it.',
  education_diplomacy_1: '{name} knows the basics of courtesy and negotiation. A start.',
  education_diplomacy_2: '{name} handles negotiations with growing confidence. They leave most tables satisfied.',
  education_diplomacy_3: '{name} is a skilled diplomat — able to defuse tension and forge alliances others thought impossible.',
  education_diplomacy_4: '{name} has mastered the art of the deal, the treaty, and the carefully worded letter.',
  education_diplomacy_5: '{name}\'s diplomatic reputation precedes them. They have talked their way out of wars and into legacies.',
  education_stewardship_1: '{name} knows the basics of managing a household\'s needs. Someone has to count the grain.',
  education_stewardship_2: '{name} handles resources with growing capability. Nothing goes to waste under their watch.',
  education_stewardship_3: '{name} runs a tight operation. Ledgers balance; supply chains hold; expenses are accounted for.',
  education_stewardship_4: '{name} has mastered the administration of resources. They can make a struggling estate profitable.',
  education_stewardship_5: '{name} is a legend of stewardship. Their mastery of coin and management borders on the miraculous.',
  education_martial_1: '{name} has had basic military training. They know which end of a sword to hold — mostly.',
  education_martial_2: '{name} has a competent grasp of warfare and its demands. Soldiers follow their lead.',
  education_martial_3: '{name} understands tactics, logistics, and the art of the campaign. They are a credible commander.',
  education_martial_4: '{name} commands with expertise. Their armies move with purpose and strike with precision.',
  education_martial_5: '{name} is a martial legend. Their name on the field is worth a hundred swords.',
  education_learning_1: '{name} has had an education — not a grand one, but a start. They read; they question.',
  education_learning_2: '{name} has studied enough to know what they do not know. That is its own kind of wisdom.',
  education_learning_3: '{name} is well-read, well-spoken, and well-regarded in learned circles.',
  education_learning_4: '{name} has mastered multiple fields of knowledge. Their mind is a library with excellent organization.',
  education_learning_5: '{name} is a scholar of legendary stature. The sum of their learning humbles most who meet them.'
};
