// ============================================================
// traits_personality.js — Personality trait definitions, stat modifiers, and flavor text.
// ============================================================

const PERSONALITY_TRAITS = [
  {
    "id": "lustful",
    "label": "Lustful",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["chaste"],
    "compat": {
        "lustful": 30,
        "gregarious": 5,
        "lifestyle_reveler": 5,
        "seducer": 5,
        "chaste": -30,
        "celibate": -30,
        "shy": -5
      }
  },
  {
    "id": "chaste",
    "label": "Chaste",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["lustful"],
    "compat": {
        "chaste": 15,
        "celibate": 15,
        "temperate": 5,
        "calm": 5,
        "lustful": -30,
        "deviant": -30,
        "lovers_pox": -5,
        "early_great_pox": -5,
        "great_pox": -5,
        "lifestyle_reveler": -5,
        "seducer": -5
      }
  },
  {
    "id": "gluttonous",
    "label": "Gluttonous",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["temperate"],
    "compat": {
        "gluttonous": 15,
        "drunkard": 5,
        "greedy": 5,
        "ambitious": 5,
        "lifestyle_reveler": 15,
        "temperate": -15
      }
  },
  {
    "id": "temperate",
    "label": "Temperate",
    "category": "personality",
    "cost": 40,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["gluttonous","excessive"],
    "compat": {
        "temperate": 15,
        "calm": 5,
        "content": 5,
        "chaste": 5,
        "gluttonous": -15,
        "excessive": -15,
        "drunkard": -5,
        "greedy": -5,
        "lustful": -5,
        "lifestyle_reveler": -15
      }
  },
  {
    "id": "greedy",
    "label": "Greedy",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["generous"],
    "compat": {
        "greedy": 5,
        "ambitious": 5,
        "generous": -30,
        "content": -15,
        "compassionate": -15
      }
  },
  {
    "id": "generous",
    "label": "Generous",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["greedy"],
    "compat": {
        "generous": 30,
        "compassionate": 15,
        "content": 5,
        "forgiving": 5,
        "greedy": -30,
        "ambitious": -5
      }
  },
  {
    "id": "lazy",
    "label": "Lazy",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["diligent"],
    "compat": {
        "lazy": 15,
        "content": 5,
        "calm": 5,
        "gluttonous": 5,
        "diligent": -15,
        "ambitious": -5,
        "eccentric": -5
      }
  },
  {
    "id": "diligent",
    "label": "Diligent",
    "category": "personality",
    "cost": 40,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {
        "diligent": 15,
        "ambitious": 5,
        "patient": 5,
        "whole_of_body": 5,
        "scholar": 5,
        "theologian": 5,
        "pensive": 5,
        "architect": 5,
        "administrator": 5,
        "avaricious": 5,
        "lazy": -15,
        "content": -5
      }
  },
  {
    "id": "wrathful",
    "label": "Wrathful",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {
        "wrathful": 5,
        "stubborn": 5,
        "honest": 5,
        "vengeful": 5,
        "calm": -15,
        "patient": -15,
        "forgiving": -5,
        "compassionate": -5,
        "eccentric": -5
      }
  },
  {
    "id": "calm",
    "label": "Calm",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["wrathful"],
    "compat": {
        "calm": 15,
        "patient": 15,
        "chaste": 5,
        "temperate": 5,
        "lazy": 5,
        "wrathful": -30,
        "impatient": -15
      }
  },
  {
    "id": "patient",
    "label": "Patient",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["impatient"],
    "compat": {
        "patient": 15,
        "calm": 15,
        "stubborn": 5,
        "temperate": 5,
        "eccentric": 5,
        "impatient": -30,
        "wrathful": -5,
        "fickle": -5
      }
  },
  {
    "id": "impatient",
    "label": "Impatient",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["patient"],
    "compat": {
        "impatient": 5,
        "wrathful": 5,
        "brave": 5,
        "patient": -15,
        "calm": -5,
        "temperate": -5,
        "eccentric": -30
      }
  },
  {
    "id": "arrogant",
    "label": "Arrogant",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["humble"],
    "compat": {
        "arrogant": 5,
        "greedy": 15,
        "ambitious": 15,
        "beauty_good_1": 5,
        "beauty_good_2": 5,
        "beauty_good_3": 5,
        "humble": -15,
        "content": -15,
        "generous": -5,
        "beauty_bad_1": -5,
        "beauty_bad_2": -5,
        "beauty_bad_3": -5
      }
  },
  {
    "id": "humble",
    "label": "Humble",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["arrogant"],
    "compat": {
        "humble": 30,
        "content": 5,
        "generous": 5,
        "compassionate": 5,
        "just": 5,
        "arrogant": -30,
        "greedy": -15,
        "ambitious": -15
      }
  },
  {
    "id": "deceitful",
    "label": "Deceitful",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["honest"],
    "compat": {
        "deceitful": 15,
        "charming": 15,
        "ambitious": 5,
        "honest": -15,
        "just": -15,
        "trusting": -15,
        "paranoid": -5,
        "compassionate": -5,
        "eccentric": -5
      }
  },
  {
    "id": "honest",
    "label": "Honest",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["deceitful"],
    "compat": {
        "honest": 30,
        "just": 15,
        "trusting": 15,
        "compassionate": 5,
        "deceitful": -30,
        "charming": -15,
        "paranoid": -15
      }
  },
  {
    "id": "craven",
    "label": "Craven",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["brave"],
    "compat": {
        "craven": 5,
        "patient": 5,
        "calm": 5,
        "content": 5,
        "brave": -15,
        "wrathful": -30,
        "sadistic": -30,
        "callous": -15,
        "impatient": -5,
        "ambitious": -5,
        "deceitful": -5
      }
  },
  {
    "id": "brave",
    "label": "Brave",
    "category": "personality",
    "cost": 40,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["craven"],
    "compat": {
        "brave": 30,
        "ambitious": 15,
        "rowdy": 15,
        "gallant": 5,
        "lifestyle_blademaster": 5,
        "strategist": 5,
        "overseer": 5,
        "craven": -30,
        "lazy": -15,
        "calm": -5,
        "content": -5
      }
  },
  {
    "id": "shy",
    "label": "Shy",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["gregarious"],
    "compat": {
        "shy": 15,
        "content": 5,
        "calm": 5,
        "craven": 5,
        "chaste": 5,
        "celibate": 5,
        "eccentric": 5,
        "gregarious": -30,
        "curious": -15,
        "wrathful": -15,
        "ambitious": -5,
        "lustful": -5
      }
  },
  {
    "id": "gregarious",
    "label": "Gregarious",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {
        "gregarious": 30,
        "curious": 15,
        "charming": 30,
        "compassionate": 15,
        "honest": 15,
        "lustful": 15,
        "lifestyle_reveler": 15,
        "diplomat": 15,
        "family_first": 15,
        "august": 15,
        "gallant": 15,
        "eccentric": 15,
        "trusting": 5,
        "shy": -15,
        "callous": -15,
        "sadistic": -15,
        "chaste": -5,
        "celibate": -5,
        "craven": -5
      }
  },
  {
    "id": "ambitious",
    "label": "Ambitious",
    "category": "personality",
    "cost": 40,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["content"],
    "compat": {
        "ambitious": 5,
        "diligent": 5,
        "greedy": 5,
        "brave": 5,
        "rowdy": 5,
        "content": -15,
        "lazy": -15,
        "craven": -15,
        "generous": -5,
        "trusting": -5
      }
  },
  {
    "id": "content",
    "label": "Content",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["ambitious"],
    "compat": {
        "content": 15,
        "lazy": 5,
        "calm": 5,
        "generous": 5,
        "forgiving": 5,
        "ambitious": -15,
        "diligent": -5,
        "greedy": -5,
        "brave": -5,
        "vengeful": -5
      }
  },
  {
    "id": "arbitrary",
    "label": "Arbitrary",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {
        "eccentric": 15,
        "arbitrary": 5,
        "fickle": 5,
        "just": -15,
        "zealous": -5,
        "stubborn": -5,
        "honest": -5
      }
  },
  {
    "id": "just",
    "label": "Just",
    "category": "personality",
    "cost": 40,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["arbitrary"],
    "compat": {
        "just": 30,
        "zealous": 15,
        "honest": 15,
        "compassionate": 15,
        "gallant": 15,
        "trusting": 5,
        "brave": 5,
        "arbitrary": -30,
        "deceitful": -15,
        "sadistic": -15,
        "callous": -15,
        "fickle": -5,
        "greedy": -5,
        "eccentric": -5
      }
  },
  {
    "id": "cynical",
    "label": "Cynical",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["zealous"],
    "compat": {
        "cynical": 30,
        "whole_of_body": 15,
        "scholar": 15,
        "theologian": 15,
        "honest": 5,
        "intellect_good_1": 5,
        "intellect_good_2": 5,
        "intellect_good_3": 5,
        "shrewd": 5,
        "zealous": -30,
        "intellect_bad_1": -15,
        "intellect_bad_2": -15,
        "intellect_bad_3": -15,
        "trusting": -5
      }
  },
  {
    "id": "zealous",
    "label": "Zealous",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["cynical"],
    "compat": {
        "zealous": 30,
        "just": 15,
        "devoted": 15,
        "ambitious": 5,
        "trusting": 5,
        "whole_of_body": 5,
        "scholar": 5,
        "theologian": 5,
        "cynical": -30,
        "craven": -15,
        "content": -5,
        "paranoid": -5,
        "drunkard": -5,
        "lifestyle_herbalist": -5,
        "lifestyle_mystic": -5,
        "eccentric": -5
      }
  },
  {
    "id": "paranoid",
    "label": "Paranoid",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["trusting"],
    "compat": {
        "paranoid": 5,
        "cynical": 5,
        "honest": 5,
        "trusting": -30,
        "forgiving": -15,
        "deceitful": -30,
        "sadistic": -30,
        "callous": -30,
        "vengeful": -30,
        "gregarious": -15,
        "lustful": -15,
        "greedy": -15,
        "ambitious": -15,
        "eccentric": -15
      }
  },
  {
    "id": "trusting",
    "label": "Trusting",
    "category": "personality",
    "cost": 10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["paranoid"],
    "compat": {
        "trusting": 15,
        "honest": 15,
        "compassionate": 5,
        "paranoid": -15,
        "deceitful": -15,
        "callous": -5,
        "sadistic": -5,
        "vengeful": -5
      }
  },
  {
    "id": "compassionate",
    "label": "Compassionate",
    "category": "personality",
    "cost": 10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["callous","sadistic"],
    "compat": {
        "compassionate": 30,
        "generous": 30,
        "honest": 15,
        "just": 15,
        "forgiving": 15,
        "trusting": 5,
        "gregarious": 5,
        "curious": 15,
        "calm": 5,
        "patient": 5,
        "eccentric": 5,
        "callous": -30,
        "sadistic": -30,
        "deceitful": -15,
        "arbitrary": -15,
        "vengeful": -15,
        "greedy": -5,
        "paranoid": -5,
        "wrathful": -5,
        "torturer": -5
      }
  },
  {
    "id": "callous",
    "label": "Callous",
    "category": "personality",
    "cost": 40,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["compassionate","sadistic"],
    "compat": {
        "callous": 5,
        "arbitrary": 5,
        "compassionate": -30,
        "curious": -5,
        "generous": -30,
        "just": -15,
        "forgiving": -15,
        "trusting": -5
      }
  },
  {
    "id": "sadistic",
    "label": "Sadistic",
    "category": "personality",
    "cost": 40,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["compassionate","callous"],
    "compat": {
        "sadistic": 15,
        "torturer": 5,
        "callous": 5,
        "arbitrary": 5,
        "compassionate": -30,
        "generous": -30,
        "just": -15,
        "forgiving": -15,
        "trusting": -5,
        "curious": -5
      }
  },
  {
    "id": "stubborn",
    "label": "Stubborn",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["eccentric","fickle"],
    "compat": {
        "patient": 5,
        "forgiving": -5,
        "fickle": -5
      }
  },
  {
    "id": "fickle",
    "label": "Fickle",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["eccentric","stubborn"],
    "compat": {
        "fickle": 5,
        "forgiving": 5,
        "stubborn": -15
      }
  },
  {
    "id": "eccentric",
    "label": "Eccentric",
    "category": "personality",
    "cost": 15,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["stubborn","fickle"],
    "compat": {
        "patient": 30,
        "arbitrary": 5,
        "shy": 5,
        "gregarious": 5,
        "compassionate": 5,
        "stubborn": -15,
        "fickle": -15,
        "zealous": -15,
        "just": -15,
        "wrathful": -15,
        "impatient": -15,
        "deceitful": -15,
        "paranoid": -15
      }
  },
  {
    "id": "vengeful",
    "label": "Vengeful",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["forgiving"],
    "compat": {
        "forgiving": -30,
        "content": -15,
        "compassionate": -5
      }
  },
  {
    "id": "forgiving",
    "label": "Forgiving",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["vengeful"],
    "compat": {
        "forgiving": 30,
        "compassionate": 15,
        "honest": 15,
        "generous": 5,
        "just": 5,
        "trusting": 5,
        "gregarious": 5,
        "calm": 5,
        "patient": 5,
        "vengeful": -30,
        "callous": -15,
        "sadistic": -15,
        "deceitful": -15,
        "arbitrary": -5,
        "paranoid": -5,
        "wrathful": -5
      }
  },
  {
    "id": "selfless",
    "label": "Selfless",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["self_serving"],
    "compat": {
        "selfless": 15,
        "compassionate": 15,
        "generous": 15,
        "humble": 10,
        "forgiving": 5,
        "just": 5,
        "self_serving": -30,
        "greedy": -15,
        "callous": -10,
        "arrogant": -10
      }
  },
  {
    "id": "self_serving",
    "label": "Self-serving",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["selfless"],
    "compat": {
        "self_serving": 5,
        "greedy": 15,
        "ambitious": 10,
        "arrogant": 10,
        "deceitful": 5,
        "selfless": -30,
        "compassionate": -20,
        "generous": -20,
        "just": -10,
        "humble": -10
      }
  },
  {
    "id": "excessive",
    "label": "Excessive",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["temperate"],
    "compat": {
        "gluttonous": 10,
        "drunkard": 10,
        "lustful": 5,
        "lifestyle_reveler": 10,
        "temperate": -30,
        "chaste": -10,
        "content": -5,
        "calm": -5
      }
  },
  {
    "id": "perceptive",
    "label": "Perceptive",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["oblivious"],
    "compat": {
        "perceptive": 15,
        "curious": 10,
        "pensive": 10,
        "paranoid": 5,
        "shrewd": 10,
        "diligent": 5,
        "oblivious": -30,
        "trusting": -5
      }
  },
  {
    "id": "oblivious",
    "label": "Oblivious",
    "category": "personality",
    "cost": -15,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["perceptive"],
    "compat": {
        "trusting": 5,
        "content": 5,
        "perceptive": -30,
        "paranoid": -15,
        "curious": -10
      }
  },
  {
    "id": "stoic",
    "label": "Stoic",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["expressive"],
    "compat": {
        "stoic": 15,
        "calm": 15,
        "patient": 10,
        "cynical": 10,
        "stubborn": 5,
        "expressive": -30,
        "zealous": -5,
        "gregarious": -10
      }
  },
  {
    "id": "expressive",
    "label": "Expressive",
    "category": "personality",
    "cost": 15,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["stoic"],
    "compat": {
        "expressive": 10,
        "gregarious": 15,
        "compassionate": 10,
        "charming": 10,
        "stoic": -30,
        "calm": -10,
        "stubborn": -5
      }
  },
  {
    "id": "calculating",
    "label": "Calculating",
    "category": "personality",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["impulsive"],
    "compat": {
        "calculating": 15,
        "patient": 15,
        "shrewd": 15,
        "cynical": 10,
        "ambitious": 5,
        "impulsive": -30,
        "trusting": -10,
        "honest": -5
      }
  },
  {
    "id": "impulsive",
    "label": "Impulsive",
    "category": "personality",
    "cost": -5,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["calculating"],
    "compat": {
        "brave": 10,
        "wrathful": 5,
        "rowdy": 10,
        "impatient": 5,
        "calculating": -30,
        "patient": -20,
        "stubborn": -10
      }
  },
  {
    "id": "worldly",
    "label": "Worldly",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["naive"],
    "compat": {
        "worldly": 15,
        "curious": 15,
        "gregarious": 10,
        "cynical": 5,
        "lifestyle_traveler": 15,
        "naive": -30,
        "trusting": -10
      }
  },
  {
    "id": "naive",
    "label": "Naive",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["worldly"],
    "compat": {
        "trusting": 10,
        "compassionate": 5,
        "zealous": 5,
        "worldly": -30,
        "cynical": -15,
        "curious": -5
      }
  },
  {
    "id": "fateful",
    "label": "Fateful",
    "category": "personality",
    "cost": 15,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["defiant"],
    "compat": {
        "fateful": 10,
        "zealous": 15,
        "content": 10,
        "humble": 5,
        "compassionate": 5,
        "defiant": -30,
        "ambitious": -10,
        "stubborn": -5
      }
  },
  {
    "id": "defiant",
    "label": "Defiant",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["fateful"],
    "compat": {
        "defiant": 10,
        "brave": 10,
        "stubborn": 15,
        "ambitious": 10,
        "wrathful": 5,
        "fateful": -30,
        "content": -15,
        "humble": -5
      }
  },
  {
    "id": "oathbound",
    "label": "Oathbound",
    "category": "personality",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["oathbreaking"],
    "compat": {
        "oathbound": 20,
        "honest": 20,
        "just": 15,
        "stubborn": 10,
        "zealous": 10,
        "humble": 5,
        "oathbreaking": -30,
        "deceitful": -20,
        "ambitious": -5
      }
  },
  {
    "id": "oathbreaking",
    "label": "Oathbreaking",
    "category": "personality",
    "cost": -15,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["oathbound"],
    "compat": {
        "deceitful": 20,
        "ambitious": 10,
        "arrogant": 5,
        "oathbound": -30,
        "honest": -20,
        "just": -20,
        "zealous": -10
      }
  },
  {
    "id": "reverent",
    "label": "Reverent",
    "category": "personality",
    "cost": 20,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["rude"],
    "compat": {
        "reverent": 15,
        "zealous": 15,
        "humble": 10,
        "just": 5,
        "compassionate": 5,
        "rude": -30,
        "arrogant": -10,
        "arbitrary": -5
      }
  },
  {
    "id": "rude",
    "label": "Rude",
    "category": "personality",
    "cost": -10,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": ["reverent"],
    "compat": {
        "honest": 10,
        "wrathful": 5,
        "arrogant": 5,
        "reverent": -30,
        "gregarious": -15,
        "compassionate": -10,
        "humble": -10
      }
  }
];

const PERSONALITY_STATS = {
  lustful: { intrigue: 2, charisma: 1, deception: 1 },
  chaste: { learning: 2, wisdom: 1 },
  gluttonous: { stewardship: -2, constitution: -1, survival: -1 },
  temperate: { stewardship: 2, constitution: 1, wisdom: 1 },
  greedy: { diplomacy: -2, investigation: 1 },
  generous: { diplomacy: 3, charisma: 1, persuasion: 1 },
  lazy: { stewardship: -1, martial: -1, intrigue: -1, diplomacy: -1, learning: -1, constitution: -1, athletics: -1 },
  diligent: { stewardship: 3, diplomacy: 2, learning: 3, intelligence: 1, wisdom: 1 },
  wrathful: { martial: 3, intrigue: -1, diplomacy: -1, strength: 1, intimidation: 2 },
  calm: { intrigue: 1, diplomacy: 1, wisdom: 2, insight: 1 },
  patient: { learning: 2, wisdom: 2, insight: 2 },
  impatient: { learning: -2, wisdom: -1 },
  deceitful: { intrigue: 4, diplomacy: -2, deception: 3, insight: 1 },
  honest: { intrigue: -4, diplomacy: 2, persuasion: 1 },
  craven: { martial: -2, intrigue: 2, prowess: -3, strength: -1, dexterity: -1, constitution: -1 },
  brave: { martial: 2, prowess: 3, strength: 1, dexterity: 1, constitution: 1, athletics: 1, intimidation: 1 },
  shy: { diplomacy: -2, learning: 1, charisma: -1, persuasion: -1 },
  gregarious: { diplomacy: 2, charisma: 1, performance: 1, persuasion: 1 },
  ambitious: { stewardship: 1, martial: 1, intrigue: 1, diplomacy: 1, learning: 1, prowess: 1, charisma: 1, persuasion: 1 },
  content: { intrigue: -1, learning: 2, wisdom: 1 },
  arbitrary: { stewardship: -2, intrigue: 3, learning: -1, wisdom: -1 },
  just: { stewardship: 2, intrigue: -3, learning: 1, wisdom: 1, insight: 1 },
  cynical: { intrigue: 2, learning: 2, insight: 2, deception: 1 },
  zealous: { martial: 2, wisdom: 1, religion: 3, persuasion: 1 },
  paranoid: { intrigue: 3, diplomacy: -1, perception: 2, insight: 1 },
  trusting: { intrigue: -2, diplomacy: 2, insight: -1 },
  compassionate: { intrigue: -2, diplomacy: 2, insight: 2, medicine: 1, animal_handling: 1 },
  callous: { intrigue: 2, diplomacy: -2, insight: -1 },
  sadistic: { intrigue: 2, prowess: 4, intimidation: 2 },
  stubborn: { stewardship: 3, constitution: 1 },
  fickle: { stewardship: -2, intrigue: 1, diplomacy: 2, wisdom: -1, charisma: -1 },
  eccentric: { diplomacy: -2, learning: 2, intelligence: 1 },
  vengeful: { intrigue: 2, diplomacy: -2, prowess: 2, intimidation: 1, insight: 1 },
  forgiving: { intrigue: -2, diplomacy: 2, learning: 1, charisma: 1, persuasion: 1 },
  selfless: { diplomacy: 2, charisma: 1, insight: 1, persuasion: 1 },
  self_serving: { intrigue: 2, stewardship: 1, deception: 1 },
  excessive: { stewardship: -2, constitution: -1, wisdom: -1 },
  perceptive: { intrigue: 1, wisdom: 1, perception: 3, insight: 2 },
  oblivious: { wisdom: -1, perception: -2, insight: -2 },
  stoic: { constitution: 1, wisdom: 1, insight: 1, intimidation: 1 },
  expressive: { diplomacy: 1, charisma: 2, performance: 2, persuasion: 1 },
  calculating: { intrigue: 2, intelligence: 1, investigation: 1, insight: 1 },
  impulsive: { intrigue: -1, wisdom: -1, dexterity: 1, athletics: 1 },
  worldly: { diplomacy: 2, intrigue: 1, intelligence: 1, history: 1, persuasion: 1 },
  naive: { intrigue: -2, insight: -1, deception: -2 },
  fateful: { wisdom: 1, religion: 1, insight: 1 },
  defiant: { intrigue: 1, constitution: 1, strength: 1, intimidation: 1 },
  oathbound: { stewardship: 2, diplomacy: 1, wisdom: 1, persuasion: 1 },
  oathbreaking: { intrigue: 2, diplomacy: -2, deception: 2 },
  reverent: { diplomacy: 1, wisdom: 1, religion: 2, insight: 1 },
  rude: { diplomacy: -2, charisma: -1, intimidation: 1 }
};

const PERSONALITY_FLAVOR = {
  lustful: '{name} is drawn to passion and desire — wherever they walk, hearts follow, and sometimes get broken along the way.',
  chaste: '{name} holds firm to a life of restraint. Whether out of principle or devotion, the flesh holds little temptation for them.',
  gluttonous: 'The finest foods, the fullest cups — {name} never learned the art of enough. A character trait that warms the heart and strains the purse.',
  temperate: '{name} drinks from life in measured sips. Self-discipline is their quiet superpower.',
  greedy: 'Gold speaks first with {name}. Every deal has a price, and they have already calculated theirs.',
  generous: '{name} gives freely — of coin, of time, of warmth. The world is a little brighter for it.',
  lazy: 'Why do today what can be done never? {name} has mastered the art of the comfortable pause.',
  diligent: '{name} does not rest when work remains. Their candles burn late, and their callouses run deep.',
  wrathful: 'Push {name} too far and the calm breaks like a storm. Their anger, when it comes, is not soon forgotten.',
  calm: '{name} weathers every tempest with the patience of old stone. Rarely flustered, rarely shaken.',
  patient: '{name} waits. And waits. And when the moment arrives, they are ready.',
  impatient: 'Waiting is a kind of torture for {name}. The world never moves fast enough for their liking.',
  arrogant: '{name} knows they are exceptional — and is not shy about it. Others may find it grating. {name} calls it honesty.',
  humble: '{name} does not seek the spotlight. They let their deeds speak, quietly and without fanfare.',
  deceitful: '{name} wears many faces. They are not dishonest out of malice perhaps — but the truth is a tool they use sparingly.',
  honest: '{name} speaks plainly, sometimes to a fault. What you see is what you get.',
  craven: 'When danger looms, {name}\'s feet find themselves eager for the door. Call it survival instinct; others call it cowardice.',
  brave: '{name} walks into the dark without checking for candles first. Courage, or perhaps a lack of imagination.',
  shy: '{name} takes time to warm to strangers. Beneath the quiet, there is often more than meets the eye.',
  gregarious: '{name} never met a room they could not work. Conversation is their native language.',
  ambitious: '{name} eyes every horizon with hunger. Where others see a ceiling, they see a floor.',
  content: '{name} does not chase the wind. They have found peace with who they are and where they stand.',
  arbitrary: '{name}\'s decisions can seem unpredictable. They march to a rhythm others can\'t quite hear.',
  just: '{name} believes in balance. Right and wrong are not abstractions to them — they are standards to be lived by.',
  cynical: '{name} has seen too much to be surprised. The world is what it is, and they are not fooled by its kindnesses.',
  zealous: '{name} is deeply devoted to their faith. Perhaps the light of their god shines brightly on them — or perhaps it burns a little.',
  paranoid: '{name} trusts carefully — perhaps too carefully. Every shadow hides a dagger in their mind.',
  trusting: '{name} sees the good in people, even when they probably should not. An admirable quality, if sometimes a dangerous one.',
  compassionate: '{name} feels the weight of others\' suffering. It is not always easy to carry, but they carry it anyway.',
  callous: '{name} does not lose sleep over others\' troubles. They have learned to separate emotion from necessity.',
  sadistic: '{name} finds a certain satisfaction in others\' pain. A dark corner of the soul that does not get much sunlight.',
  stubborn: '{name} once makes up their mind, kingdoms could not move them. Whether that is strength or flaw depends on the day.',
  fickle: '{name} changes course like wind changes direction — often and without warning. Adaptable, some say. Unreliable, say others.',
  eccentric: '{name} defies easy description. They live by their own logic, and occasionally it is brilliant.',
  vengeful: '{name} does not forget. An offense made against them is quietly filed away and never discarded.',
  forgiving: '{name} lets go of grievances, though not always easily. They believe in second chances.',
  selfless: '{name} gives without tallying the cost. The needs of others weigh heavier than their own, and they have never resented it.',
  self_serving: '{name} tends to their own interests first. It is not malice — it is simply their nature, and a practical one at that.',
  excessive: '{name} does not know when to stop. Whatever they pursue, they pursue with a thoroughness that borders on too much.',
  perceptive: '{name} sees what others miss. The faint tells, the hesitated breath, the slight shift of weight — all filed away quietly.',
  oblivious: '{name} moves through the world with a certain comfortable unawareness. What they do not notice cannot trouble them.',
  stoic: '{name} does not wear their heart on their sleeve. They endure, they persevere, and they rarely show the cost.',
  expressive: '{name} wears every feeling plainly. There is no reading between the lines — what they feel, you will know.',
  calculating: '{name} measures before they cut. Every decision is a puzzle considered carefully before the pieces fall.',
  impulsive: '{name} acts, then thinks. It has served them sometimes. Other times, they are still living with the consequences.',
  worldly: '{name} has moved in enough circles to understand how the world works. Experience does not lie.',
  naive: '{name} has not yet been properly disappointed by the world. There is something almost beautiful in that.',
  fateful: '{name} believes the path was laid before they arrived. They do not resist destiny — they try to read it.',
  defiant: '{name} does not accept what others say must be. Limits, fates, edicts — all of them feel like challenges to them.',
  oathbound: '{name} does not give their word lightly. And when they do, they mean every syllable of it.',
  oathbreaking: '{name} understands that vows are made under circumstances that change. Principles, for them, have flexibility built in.',
  reverent: '{name} carries a deep respect for what came before. Tradition, people, the sacred — they do not treat these things lightly.',
  rude: '{name} says what they mean, and means what they say, at full volume and without ceremony. It is not always welcome.'
};
