// ============================================================
// traits_commander.js — Commander/military trait definitions, stat modifiers, and flavor text.
// ============================================================

const COMMANDER_TRAITS = [
  {
    "id": "logistician",
    "label": "Logistician",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "military_engineer",
    "label": "Military Engineer",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "aggressive_attacker",
    "label": "Aggressive Attacker",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "unyielding_defender",
    "label": "Unyielding Defender",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "forder",
    "label": "Forder",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "flexible_leader",
    "label": "Flexible Leader",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "desert_warrior",
    "label": "Desert Warrior",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "jungle_stalker",
    "label": "Jungle Stalker",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "reaver",
    "label": "Reaver",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "holy_warrior",
    "label": "Holy Warrior",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "open_terrain_expert",
    "label": "Open Terrain Expert",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "rough_terrain_expert",
    "label": "Rough Terrain Expert",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "forest_fighter",
    "label": "Forest Fighter",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "cautious_leader",
    "label": "Cautious Leader",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "organizer",
    "label": "Organizer",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "savior",
    "label": "Savior",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "infiltration_specialist",
    "label": "Infiltration Specialist",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "master_ambusher",
    "label": "Master Ambusher",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "water_expert",
    "label": "Water Expert",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "navigator",
    "label": "Navigator",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "bridge_master",
    "label": "Bridge Master",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "plains_rider",
    "label": "Plains Rider",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "marsh_specialist",
    "label": "Marsh Specialist",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "winter_soldier",
    "label": "Winter Soldier",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "highlander",
    "label": "Highlander",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "volcanic_survivor",
    "label": "Volcanic Survivor",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "forest_expert",
    "label": "Forest Expert",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "woodland_tracker",
    "label": "Woodland Tracker",
    "category": "commander",
    "cost": 25,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "conqueror",
    "label": "Conqueror",
    "category": "commander",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "grand_marshal",
    "label": "Grand Marshal",
    "category": "commander",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "shadow_general",
    "label": "Shadow General",
    "category": "commander",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  },
  {
    "id": "iron_bulwark",
    "label": "Iron Bulwark",
    "category": "commander",
    "cost": 30,
    "group": null,
    "level": null,
    "genetic": false,
    "physical": false,
    "opposites": [],
    "compat": {}
  }
];

const COMMANDER_STATS = {
  logistician: { stewardship: 2, intelligence: 1, investigation: 1 },
  military_engineer: { stewardship: 1, martial: 1, intelligence: 2, investigation: 1 },
  aggressive_attacker: { martial: 2, prowess: 2, strength: 1, dexterity: 1, athletics: 1 },
  unyielding_defender: { martial: 2, constitution: 2, strength: 1 },
  forder: { martial: 1, athletics: 1, survival: 1 },
  flexible_leader: { martial: 1, diplomacy: 1, wisdom: 1, insight: 1, charisma: 1 },
  desert_warrior: { martial: 1, prowess: 1, survival: 3, perception: 1 },
  jungle_stalker: { martial: 1, prowess: 1, dexterity: 2, stealth: 3, survival: 2, perception: 1 },
  reaver: { martial: 2, prowess: 2, strength: 1, intimidation: 2, athletics: 1 },
  holy_warrior: { martial: 2, prowess: 1, strength: 1, religion: 2, intimidation: 1 },
  open_terrain_expert: { martial: 1, dexterity: 1, athletics: 1, perception: 1 },
  rough_terrain_expert: { martial: 1, survival: 2, athletics: 1 },
  forest_fighter: { martial: 1, dexterity: 1, stealth: 2, survival: 1, nature: 1 },
  cautious_leader: { martial: 1, diplomacy: 1, wisdom: 1, insight: 2 },
  organizer:                { stewardship: 1, martial: 1, intelligence: 1, insight: 1 },
  savior:                   { martial: 1, medicine: 2, charisma: 2, diplomacy: 1, religion: 1 },
  infiltration_specialist:  { stealth: 3, deception: 2, insight: 2, dexterity: 1 },
  master_ambusher:          { martial: 2, stealth: 2, dexterity: 2, perception: 2, prowess: 1 },
  water_expert:             { martial: 1, survival: 2, athletics: 1, perception: 1 },
  navigator:                { intelligence: 2, perception: 2, survival: 1, investigation: 1 },
  bridge_master:            { stewardship: 2, martial: 1, intelligence: 2, investigation: 2 },
  plains_rider:             { martial: 2, dexterity: 2, athletics: 2, perception: 1 },
  marsh_specialist:         { survival: 3, dexterity: 2, stealth: 2, perception: 1 },
  winter_soldier:           { constitution: 3, survival: 2, martial: 1, athletics: 1 },
  highlander:               { constitution: 2, strength: 2, athletics: 3, survival: 2 },
  volcanic_survivor:        { constitution: 3, survival: 3, martial: 1, wisdom: 1 },
  forest_expert:            { survival: 2, nature: 2, perception: 2, stealth: 1 },
  woodland_tracker:         { perception: 3, stealth: 3, nature: 2, dexterity: 1 },
  conqueror:                { martial: 3, prowess: 2, intimidation: 3, stewardship: 2, strength: 1 },
  grand_marshal:            { martial: 3, diplomacy: 2, intelligence: 2, wisdom: 2, charisma: 2 },
  shadow_general:           { intrigue: 3, martial: 2, stealth: 3, deception: 2, perception: 2, insight: 1 },
  iron_bulwark:             { constitution: 2, martial: 2, prowess: 2, religion: 2, stewardship: 2, intimidation: 2 },
};

const COMMANDER_FLAVOR = {
  logistician: '{name} ensures supplies reach the right place at the right time. The unseen backbone of any campaign.',
  military_engineer: '{name} builds siege engines and fortress plans. They see war as a problem of design.',
  aggressive_attacker: '{name} presses the fight before the enemy finds its footing. Momentum is their weapon.',
  unyielding_defender: '{name} does not break easy. They hold lines others would have abandoned.',
  forder: '{name} has learned to move armies through rivers and difficult terrain without losing half of them along the way.',
  flexible_leader: '{name} adapts to the battlefield\'s demands. A style that cannot be read is hard to counter.',
  desert_warrior: '{name} has learned to fight where others wilt. The desert shapes those who survive it.',
  jungle_stalker: '{name} knows how to vanish and strike in dense terrain. Patience and silence are their weapons.',
  reaver: '{name} fights with a brutality that leaves impressions, and not the diplomatic kind.',
  holy_warrior: '{name} fights with faith as a second shield. Whether that makes them stronger or only more certain is a matter of perspective.',
  open_terrain_expert: '{name} excels on open ground: cavalry charges, pitched battles, wide engagements.',
  rough_terrain_expert: '{name} uses broken ground to their advantage. Uneven fields favor the prepared.',
  forest_fighter: '{name} knows how to use trees as cover and shadows as allies.',
  cautious_leader: '{name} does not rush. They fight only when the odds are tilted firmly in their favor.',
  organizer:               '{name} ensures the army arrives fed, organized, and on time. That wins more battles than heroics.',
  savior:                  '{name} is the reason soldiers march on. A rallying presence at the worst possible moment: part commander, part medic, part myth.',
  infiltration_specialist: '{name} moves through enemy positions like shadow on shadow. They know how to be unseen, unheard, and unremembered.',
  master_ambusher:         '{name} turns favorable ground into a trap. By the time the enemy realizes the danger, it is already too late.',
  water_expert:            '{name} is at home on the water in a way most soldiers never are. Ships, currents, tides, and weather at sea are not mysteries to them but tools.',
  navigator:               '{name} reads the stars, the wind, and the swell of open water like a map. They have guided ships through conditions that turned others back.',
  bridge_master:           '{name} knows bridges completely. They can build one fast, hold one against determined resistance, or bring one down before the enemy reaches the other side.',
  plains_rider:            '{name} commands wide-open ground with cavalry ease. The plains are where they are most dangerous.',
  marsh_specialist:        '{name} has learned to move through bog and wetland like a reed in the wind. Silence and patience are second nature.',
  winter_soldier:          '{name} does not slow when the cold comes. They have marched through blizzards and kept armies alive to fight in spring.',
  highlander:              '{name} was forged in the mountain passes. They climb where others falter and hold terrain that should be indefensible.',
  volcanic_survivor:       '{name} has endured environments that would break most. Heat, ash, and instability are merely conditions to manage.',
  forest_expert:           '{name} understands forests the way a huntsman understands their quarry. The trees offer no resistance to them.',
  woodland_tracker:        '{name} does not track prey. They follow armies through tangled growth without being seen or heard.',
  conqueror:               '{name} does not merely win battles. They end wars. Where they march, resistance collapses and nations fall quiet.',
  grand_marshal:           '{name} has mastered every dimension of warfare. They do not specialize. They command, adapt, and decide.',
  shadow_general:          '{name} is a ghost with an army. Enemies do not know they have lost until it is already over.',
  iron_bulwark:            '{name} is a wall. A wall that prays, plans, and never yields. To break through them you must first break through everything they stand for.',
};
